### ISSUE TITLE
Improve the ability to log out from creation and 404 pages. 

### ISSUE THREAD

**Issue by kmcurry** [kmcurry/3Scape#302]
Currently when I am successfully logged in and creating a scape there is no way for me to sign out. Also, when I attempt to visit a page that doesn't exist the current log out button located on the 404 page only redirects me to a sign up page but never actually logs me out.

**Comment by jperez757** [comment]
Steps to recreate the issues above: 
1) Visit the 3scape website but remain logged out.

2) Add the /egypt extension to your url and you should land on the /login page, which should happen when you are logged out

3) Successfully log in and add /egypt to your url and you should land on the Egyptian scape, which should happen

4) Attempt to log out from the Egyptian scape but there is no button to log out 

5) Change the /egypt extension to any page that doesn't exist (/bleh for example), you land on the 404 page

6) Click on the log out button. This lands you on the /signup page and you "should" be logged out.

7) Revisit the /egypt scape, You should not be able to since you should be logged out. /egypt works though

8) Now change the /egypt extension to /profile. The profile page for the email address you logged in with shows up. You are never actually logged out.

**Comment by kmcurry** [comment]
Great job tracking this down. What fix do you propose?

**Comment by jperez757** [comment]
I was just reading the Retention Chart invitation. I know the main goal is to keep users using our product however as far as I know the only available way to log out is to go to a 404 page. At least that's the only log out button I remember seeing. It's a bit unintuitive. First off there is a simple change that can be made in the 404.ejs file that will successfully log a user out and redirect them to the sign in page. The user will then be forced to log in to an account if they want to visit any existing 3scape like intended. The second idea was to add a log out button on the navigation bar when a user is currently creating or viewing a 3scape.

**Comment by katlandreth** [comment]
Seems like there are two issues here.

1) The user has no way to log out while logged in (it's unlikely that they will think to force a 404 page to find a log out button).

2) The log out button that's on the 404 page does not work as expected (redirection to login page works, actually logging the user out does not work)

Issue 1 - It's good for user experience to give them a way to escape and a way to navigate to all relevant areas whenever they are logged in. The exception is when you're deliberately guiding a user through a path like a checkout process when you don't want them to abandon the cart mid-checkout. 

Suggestion - add log out button to all pages a user has access to while logged in. The convention is to put log in/out buttons on the far right of the nav bar but there could be reasons to place it elsewhere.

Issue 2 - It could be worth considering removing the log out button from the 404 page. We could try to guide the user back into an area they can use rather than giving them a way to jump ship immediately. Could we give the user suggestions about where they can go within 3Scape instead?

**Comment by jperez757** [comment]
Well there is also a "To 3Scape" button on the 404 page but that redirects the user to a create page. I don't know where else we could, or rather should, redirect them.

**Comment by katlandreth** [comment]
Newsletter, Blog, or their profile page maybe? Since there aren't a ton of pages, maybe we could add links for all of the available pages?

**Comment by katlandreth** [comment]
Envato (a company that has a family of stock resource websites)  has some guidelines for 404 pages that I like. They're suggestions, not hard and fast rules. 

>Anatomy of a Good 404 Page
Having a creative or humorous 404 can certainly grab the attention of your users, but from a functionality point of view it might not be a great 404 page design. There are some fundamental things you should consider having on every 404 page:
* Why the 404 page is being shown.
* What the user can do next. Here are somethings to consider:
   * Provide an easy way to go to the homepage.
   * Show some popular/related items your visitors might be interested in.
   * Give them the ability to search for what they want.
   * Make it easy for them to report an issue.
* Leave a lasting impression.
* Stick to your overall brand and design guidelines.
* Header response should be a 404.
* Consider making the 404 page context-sensitive.
> -Envato

http://marketblog.envato.com/trends/anatomy-of-a-404-error-page-get-your-inspiration-from-the-best-404-pages/

**Comment by jperez757** [comment]
That is a very informative link! Thank you! It might also be worth noting that Kat and I discussed the possibility of adding a profile page button on the create page navigation bar as well. It seems like an appropriate spot to place one. What do you think Kevin?

**Comment by katlandreth** [comment]
No problem :)

**Comment by jperez757** [comment]
This is what the new navigation bar looks like on my side after taking Kats advice. 
![screen shot 2015-02-12 at 9 04 17 pm](https://cloud.githubusercontent.com/assets/10623892/6181173/3cb32f2c-b2fd-11e4-9eb2-f6ef9ec3ffff.png)

**Comment by jperez757** [comment]
This is the what the new 404 page looks like on my side after taking Kats advice. 
![screen shot 2015-02-12 at 9 29 08 pm](https://cloud.githubusercontent.com/assets/10623892/6181252/374960dc-b2fe-11e4-9165-c6c7705cf367.png)

**Comment by jperez757** [comment]
I added 404 to the browser tab and as a header above the quote.

**Comment by katlandreth** [comment]
I just noticed that "These aren't the Scapes you're looking for" is a Quote attributed to Kevin. That made me lol :)

**Comment by kmcurry** [comment]
Getting caught up here. @katlandreth that's not original to me, ex., https://github.com/;asdhg;al

@jperez757 We have the image & font for the 404 from @herogerik. I'll add to the repo momentarily so you can implement the [designed page](https://drive.google.com/file/d/0B9aAGmd9iudhMzNlcTdNaG1XODQ/view?usp=sharing)

@jperez757 @katlandreth @herogerik On that screen capture of 3Scape: It's not showing the fonts for those buttons on the toolbar. The toolbar is a lot wider when the buttons are there. On my screen I won't have enough room for two more links to the right. That said, we are starting over with a clean slate on this view. Bottom line: if you can fit the links on the current layout then great. If not, don't worry about it for now.

**Comment by katlandreth** [comment]
Yeah, I knew it was from the GitHub 404 but I like the attribution bit. Imagining Kevin with Oculus on in a jedi robe like the octocat :)  I actually do like the idea of having the message be from Kevin, especially if it's a little funny/silly. It creates a connection between the creator and the user.

**Comment by kmcurry** [comment]
:grin:
