### ISSUE TITLE
Design Apply Physics

### ISSUE THREAD

**Issue by kmcurry** [kmcurry/3Scape#305]
Design the experience of applying physics in 3Scape.

* Models can be individually added to and removed from the Physics Simulator
* Physics can be turned on and off
* Should physics apply to everything by default?

**Comment by kmcurry** [comment]
@mbrazell what are our choices for physical properties? Do we have things like bounciness? What about negative density, example to make a balloon float.

**Comment by mbrazell** [comment]
I haven't explored this yet, but there are other properties that can be set.

**Comment by kmcurry** [comment]
YAY! PROPERTIES!

On Tue, Feb 10, 2015 at 10:26 AM, Michael Chase Brazell <
notifications@github.com> wrote:

> I haven't explored this yet, but there are other properties that can be
> set.
>
> On Tue, Feb 10, 2015 at 10:10 AM, Kevin Curry <notifications@github.com>
> wrote:
>
> > @mbrazell <https://github.com/mbrazell> what are our choices for
> physical
> > properties? Do we have things like bounciness? What about negative
> density,
> > example to make a balloon float.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kmcurry/3Scape/issues/305#issuecomment-73714809>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kmcurry/3Scape/issues/305#issuecomment-73718121>.
>



-- 
Kevin Curry
Virginia Beach, VA

3Scape begins @ http://3Scape.me

**Comment by mbrazell** [comment]
:D

**Comment by katlandreth** [comment]
Questions:  

Could/should there be environmental forces? IE random air disturbances that cause a balloon to float about slightly instead of remaining perfectly static, increased friction of objects moving through different environments like water or sand if those environments are available.  These might convey the kinds of physics available to the user even before they discover the controls to change them.

Should all physics or physical properties be user editable, or should there be some objects or environments with fixed properties? If an environment had its own forces, should a user be able to adjust them? Could a user make a cow that floats or bounces? 

Should the user be able to adjust the surface properties of an object such as making it smooth vs rough (more or less friction)?

Does it make sense to put information/controls about an object's physics in the same interface for the objects orientation, color, texture etc? I'm thinking of an Info panel, or HUD that conveys the physical characteristics of an object.

**Comment by mbrazell** [comment]
Not sure yet how to do something like random air disturbances.  But if you
wanted something like that it could be an invisible object that exerted
forces on the visible ones.  Friction is one of the physical properties you
can set, but which I have yet to code support for (currently only mass is
supported).

I think all properties should be editable.  Physical properties should be
grouped together in their own section.

**Comment by katlandreth** [comment]
That actually leads me to another question. Are we using "real" physics or "faked" physics? 

In other words, are movements calculated using something similar to a formula in physics, or is the appearance of physics "faked"? For example, there might be ease applied when an object speeds up or slows down but it might not be related to the mass of the object. 

Here's a use case - I want to build a flywheel. Can I expect that a very heavy disk would continue spinning for a long time from inertia, or should I expect it to slow and stop without regard to its mass?

**Comment by mbrazell** [comment]
The library I'm using is a javascript version of Bullet physics, which Nasa is
using in their new open source Tensegrity Robotics Toolkit.  So I'd say
it's most likely "real" :)

Once I get deeper into the capabilities of the library I think we'll be
able to do just about anything physically related.

BTW, I'm nearly finished with Issue #79.  I have objects stopping when they
collide during object inspection, which I'm pretty stoked about.

:)

Michael

**Comment by katlandreth** [comment]
Awesome :) I was hoping you would say something like that.

**Comment by kmcurry** [comment]
We're addressing this with the Mass button-dial on the Actions Bar.

Clicking adds or removes the selected Part from Physics. Dialing increases or decreases the mass of the selected Part.

![screen shot 2015-04-26 at 11 58 26 am](https://cloud.githubusercontent.com/assets/69151/7337997/9bad13a2-ec0b-11e4-96b4-88021b00dcdf.png)
